[site]
title = "Hanchen Yang"
description = "PhD Candidate"
favicon = "/favicon.png"
last_updated = "December 25, 2025"

[author]
name = "Hanchen Yang"
title = "PhD Candidate"
institution = [
  "Tongji University",
  "Shanghai"
]
avatar = "/bio1.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "neobest@foxmail.com"

google_scholar = "https://scholar.google.com/citations?user=74ypeYgAAAAJ&hl=zh-CN"
orcid = ""
github = "https://github.com/Neoyanghc"
linkedin = "https://www.linkedin.com/in/%E6%B6%B5%E6%99%A8-%E6%9D%A8-230489373/"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "CV"
type = "link"
target = "cv"
href = "/cv.pdf"
